# Generated by Django 5.2.12 on 2026-03-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlantImage",
        ),
    ]
