# Generated by Django 5.2.12 on 2026-03-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_scanresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="supabase_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
