# Generated by Django 5.2.12 on 2026-03-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_supabase_path_to_scanresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="plant_image",
        ),
        migrations.RemoveField(
            model_name="scanresult",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlantImage",
        ),
        migrations.DeleteModel(
            name="ScanResult",
        ),
    ]
